### ISSUE TITLE
Any plans to release a new recipe for Chinese corpus?

### ISSUE THREAD

**Issue by liyongze** [k2-fsa/icefall#112] opened 2021-11-09 03:02 UTC

**Comment by csukuangfj** [comment] 2021-11-09 03:03
There is an ongoing PR for the AISHELL dataset. Will be ready soon, I think. @pkufool

**Comment by pingfengluo** [comment] 2021-11-17 09:26
there is a PR #123

**Comment by liyongze** [comment] 2021-11-18 02:42
> there is a PR #123

thanks~

**Comment by liyongze** [comment] 2021-11-18 02:42
> There is an ongoing PR for the AISHELL dataset. Will be ready soon, I think. @pkufool

thanks~

**Comment by liyongze** [comment] 2021-11-18 02:42
> There is an ongoing PR for the AISHELL dataset. Will be ready soon, I think. @pkufool

thanks~

**Comment by csukuangfj** [comment] 2021-11-18 02:45
It has been merged. You can find it at https://github.com/k2-fsa/icefall/tree/master/egs

**Comment by tz301** [comment] 2021-11-20 15:08
That's very cool work.

When I see the aishell document and reproduce it, I find my att loss has obvious mismatch (much higher) with that in the tutorial docs (ctc loss is ok). I found that was caused by the change of LabelSmoothing algorithm in [https://github.com/k2-fsa/icefall/pull/109](https://github.com/k2-fsa/icefall/pull/109). Maybe @pkufool can help to update that? I'm a little confusing at first glance. So maybe also for other new users.

Also, if there will be some scripts to deal with both Chinese and English, that will be very great. Maybe combine bpe for English and char for Chinese?. Chinese with English (code-switch) is so common today!

**Comment by csukuangfj** [comment] 2021-11-20 15:47
> When I see the aishell document and reproduce it, I find my att loss has obvious mismatch (much higher) with that in the tutorial docs (ctc loss is ok)

Please see https://github.com/k2-fsa/icefall/issues/107

Before the change, the label smoothing loss has an additional term
```
q * log(q)
```
which is negative as q is in the range (0, 1); therefore the loss before the change is smaller, but it should not affect your final WER.

**Comment by pkufool** [comment] 2021-11-22 01:26
@tz301  Thanks, will update the documents.

**Comment by pkufool** [comment] 2021-11-22 01:31
> Also, if there will be some scripts to deal with both Chinese and English, that will be very great. Maybe combine bpe for English and char for Chinese?. Chinese with English (code-switch) is so common today!

Thanks, it is a good idea, will consider adding code-switch recipe.  You are very welcome to contribute this recipe as well, if you have time.

**Comment by tz301** [comment] 2021-11-22 05:40
> @tz301 Thanks, will update the documents.

@pkufool  I have reproduce the results, excellent!

Some advice is that valid loss is missed, since the data per epoch is so small and valid loss computation will be skiped. During my reproduction, I have change valid log interval to 1000 and we can see valid loss on tensorboard below. CER is nearly the same (4.24%), compared with master (4.26%). 
![pd](https://user-images.githubusercontent.com/35760938/142806611-4b6807cf-93f2-470d-875f-33b99f7ca975.png)

**Closed** 2024-03-20 18:47 UTC
