### ISSUE TITLE
New tedlium3 conformet_ctc recipe problem

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#800] opened 2023-01-01 14:40 UTC
Hello guys,

I am trying new  tedlium3 conformet_ctc recipe which was lately added to icefall. I created following script to run training and decoder together:

export CUDA_VISIBLE_DEVICES="0,1,2,3"

./conformer_ctc2/train.py \
    --world-size 4 \
    --num-epochs 40 \
    --exp-dir conformer_ctc2/exp \
    --max-duration 150 \
    --use-fp16 true

epoch=38
avg=26

## ctc decoding
./conformer_ctc2/decode.py \
  --method ctc-decoding \
  --exp-dir conformer_ctc2/exp \
  --lang-dir data/lang_bpe_500 \
  --result-dir conformer_ctc2/exp \
  --max-duration 500 \
  --epoch $epoch \
  --avg $avg

Its behaviour is weird. After 3 days of training, and after the training was finished I got following messages. It seems that directory ~/icefall/egs/tedlium3/ASR/conformer_ctc2/exp was completed deleted. And all outputs that were created during the training were deleted. Could you help please.

2022-12-30 08:21:00,987 INFO [train.py:990] (3/4) Done!
2022-12-30 08:21:01,016 INFO [train.py:990] (2/4) Done!
2022-12-30 08:21:01,028 INFO [train.py:990] (1/4) Done!
2022-12-30 08:21:01,030 INFO [checkpoint.py:75] (0/4) Saving checkpoint to conformer_ctc2/exp/epoch-40.pt
2022-12-30 08:21:04,603 INFO [train.py:990] (0/4) Done!
fatal: detected dubious ownership in repository at '/fsx_new/Alex/tmp1/icefall'
To add an exception for this directory, call:

        git config --global --add safe.directory /fsx_new/Alex/tmp1/icefall
fatal: detected dubious ownership in repository at '/fsx_new/Alex/tmp1/icefall'
To add an exception for this directory, call:

        git config --global --add safe.directory /fsx_new/Alex/tmp1/icefall
fatal: detected dubious ownership in repository at '/fsx_new/Alex/tmp1/icefall'
To add an exception for this directory, call:

        git config --global --add safe.directory /fsx_new/Alex/tmp1/icefall
2022-12-30 08:21:08,389 INFO [decode.py:646] Decoding started
2022-12-30 08:21:08,390 INFO [decode.py:647] {'subsampling_factor': 4, 'feature_dim': 80, 'search_beam': 15, 'output_beam': 8, 'min_active_states': 10, 'max_active_states': 7000, 'use_double_scores': True, 'env_info': {'k2-version': '1.21', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': 'c3a7404e0d9da4d8d99f3f15c54d80b321c1b960', 'k2-git-date': 'Mon Oct 31 04:45:41 2022', 'lhotse-version': '1.10.0.dev+git.96884c9.clean', 'torch-version': '1.12.1', 'torch-cuda-available': True, 'torch-cuda-version': '11.3', 'python-version': '3.7', 'icefall-git-branch': None, 'icefall-git-sha1': None, 'icefall-git-date': None, 'icefall-path': '/fsx_new/Alex/tmp1/icefall', 'k2-path': '/opt/conda/lib/python3.7/site-packages/k2-1.21.dev20221102+cuda11.3.torch1.12.1-py3.7-linux-x86_64.egg/k2/__init__.py', 'lhotse-path': '/opt/conda/lib/python3.7/site-packages/lhotse/__init__.py', 'hostname': 'bdcf5ab79459', 'IP address': '172.17.0.3'}, 'epoch': 38, 'iter': 0, 'avg': 26, 'method': 'ctc-decoding', 'use_averaged_model': True, 'num_paths': 100, 'nbest_scale': 0.5, 'exp_dir': PosixPath('conformer_ctc2/exp'), 'lang_dir': PosixPath('data/lang_bpe_500'), 'lm_path': PosixPath('data/lm/G_4_gram.pt'), 'result_dir': PosixPath('conformer_ctc2/exp'), 'num_encoder_layers': 24, 'num_decoder_layers': 6, 'att_rate': 0.8, 'dim_feedforward': 1536, 'nhead': 8, 'dim_model': 384, 'manifest_dir': PosixPath('data/fbank'), 'max_duration': 500, 'bucketing_sampler': True, 'num_buckets': 30, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': False, 'shuffle': True, 'return_cuts': True, 'num_workers': 2, 'enable_spec_aug': True, 'spec_aug_time_warp_factor': 80, 'enable_musan': True}
2022-12-30 08:21:08,616 INFO [lexicon.py:168] Loading pre-compiled data/lang_bpe_500/Linv.pt
2022-12-30 08:21:08,688 INFO [decode.py:657] device: cuda:0
2022-12-30 08:21:11,451 INFO [decode.py:836] Calculating the averaged model over epoch range from 12 (excluded) to 38
Traceback (most recent call last):
  File "./conformer_ctc2/decode.py", line 899, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./conformer_ctc2/decode.py", line 844, in main
    device=device,
  File "/workspace/icefall/icefall/checkpoint.py", line 424, in average_checkpoints_with_averaged_model
    state_dict_start = torch.load(filename_start, map_location=device)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'conformer_ctc2/exp/epoch-12.pt'
fatal: detected dubious ownership in repository at '/fsx_new/Alex/tmp1/icefall'
To add an exception for this directory, call:

**Comment by AlexandderGorodetski** [comment] 2023-01-01 14:53
Guys, I am pretty sure that there is some problem with decode.py.
I have created several directories under directory exp/ and once I run decode.py all these subdirectories are deleted. Could you help please.

**Comment by AlexandderGorodetski** [comment] 2023-01-01 14:57
Guys, I found the lines that cause the deletion problem.

You can see in decode.py following lines:

    if args.result_dir.is_dir():
        shutil.rmtree(args.result_dir)
    args.result_dir.mkdir()

Could you help with this issue.

**Comment by csukuangfj** [comment] 2023-01-01 14:57
> once I run decode.py all these subdirectories are deleted. Could you help please.

Could you use `pdb` to run decode.py step by step and and try to find at which line `exp` gets deleted?

**Comment by videodanchik** [comment] 2023-01-01 15:09
I know why this happen, it's because I added an opportunity to save decoding results in a separate folder and it cleans it in the begininng of decode.py script. By default I set `--result-dir` to `conformer_ctc2/exp`, the same as `--exp-dir`, it was a mistake. @AlexandderGorodetski could you please try decode.py with  `--result-dir`  equal to `conformer_ctc2/exp/results`. It should help. I'm sorry that you removed all your models because of this bug, with 4 GPUs it should take less than 2 days to retrain the model.

**Comment by videodanchik** [comment] 2023-01-01 15:10
@csukuangfj I can modify the default value for `--result-dir` in `decode.py` to avoid this problem in the future.

**Comment by AlexandderGorodetski** [comment] 2023-01-01 15:18
Following lines delete the exp directory

if args.result_dir.is_dir():
    shutil.rmtree(args.result_dir)
args.result_dir.mkdir()

**Comment by videodanchik** [comment] 2023-01-01 15:21
@AlexandderGorodetski Yes, I know, please make `--result-dir` different from your `--exp-dir` and it will work.

**Comment by csukuangfj** [comment] 2023-01-01 15:35
I suggest that we delete
https://github.com/k2-fsa/icefall/blob/67ae5fdf2bf2b09d2ce9e5acb7dab12b2d2fc441/egs/tedlium3/ASR/conformer_ctc2/decode.py#L638-L639

and change
https://github.com/k2-fsa/icefall/blob/67ae5fdf2bf2b09d2ce9e5acb7dab12b2d2fc441/egs/tedlium3/ASR/conformer_ctc2/decode.py#L640
to
```python3
 args.result_dir.mkdir(exist_ok=True)
```

Even if we set the default value of `--result-dir` to be different from `--exp-dir`, there is still a chance
that someone provides the same value for both `--result-dir` and `--exp-dir`. It is better not to delete things in `decode.py`.

**Comment by videodanchik** [comment] 2023-01-02 01:22
@AlexandderGorodetski Try out the latest master, the problem is fixed, also feel free to close this issue if everything works fine.

**Closed** 2023-01-02 15:15 UTC
