### ISSUE TITLE
kaldi feats loaded into model training too slow

### ISSUE THREAD

**Issue by Aurora-6** [k2-fsa/icefall#633] opened 2022-10-24 04:20 UTC
How can I use Kaldi-style dataset (including feats.scp) to generate *.jsonl.gz for icefall training scripts? If convenient, please share a specific script for reference？Thanks a lot!
I do it in this way (https://github.com/k2-fsa/icefall/issues/510#issuecomment-1208003550).However, it takes a long time to train an epoch because the data read time is too long. kaldi_native_io takes long time.

**Comment by Aurora-6** [comment] 2022-10-24 04:21
only loaded data, the log

**Comment by Aurora-6** [comment] 2022-10-24 04:23
only read data, max duration=100, the log
![image](https://user-images.githubusercontent.com/55911878/197448123-771514a2-c346-44a9-88b1-c597fbfe4ada.png)

**Comment by Aurora-6** [comment] 2022-10-24 04:33
@pzelasko  Please help to look at this problem about read kaldi feats，Thanks a lot!

**Comment by pzelasko** [comment] 2022-10-24 20:48
IIRC the issue is that kaldi_native_io would read the whole feats.scp file to memory every time you load one of the feature arrays. This doesn't scale well to large datasets.

I think one possible fix is to take each feats.scp line, copy its contents (`<utt-id> path/to/feats.ark:<numeric-offset>`) to the relevant `Features` object in Lhotse, and read from the feats.ark directly (if `kaldi_native_io` supports that), ignoring feats.scp entirely. Maybe you could find some time and make a PR in Lhotse with that change..?

**Comment by Aurora-6** [comment] 2022-10-25 14:15
> IIRC the issue is that kaldi_native_io would read the whole feats.scp file to memory every time you load one of the feature arrays. This doesn't scale well to large datasets.
> 
> I think one possible fix is to take each feats.scp line, copy its contents (`<utt-id> path/to/feats.ark:<numeric-offset>`) to the relevant `Features` object in Lhotse, and read from the feats.ark directly (if `kaldi_native_io` supports that), ignoring feats.scp entirely. This change would be done in `KaldiReader` and lhotse's kaldi import function. Maybe you could find some time and make a PR in Lhotse with that change..?

My solution is to read the kaldi feats with kaldi_native_io instead of kaldi_native_io. In this way, the loaded speed of the kaldi features is comparable to that of the saved lilcim_chunky features. It's nice to large dataset. Here I use 2wh dataset with batch max duration setting to 100. The effect as shown below.

**Comment by csukuangfj** [comment] 2022-10-25 15:08
Why does the above change make it read faster?

**Comment by csukuangfj** [comment] 2022-10-25 15:18
I see the issue.

We are using random access reader inside the feature reader. If we replace the storage path with an ark:offset, we can seek to it directly, which is faster.

**Comment by Aurora-6** [comment] 2022-10-25 15:26
> I see the issue.
> 
> We are using random access reader inside the feature reader. If we replace the storage path with an ark:offset, we can seek to it directly, which is faster.

Yes. It avoids loading the whole feats.scp file to find the feature of every audios.

**Comment by csukuangfj** [comment] 2022-10-26 02:27
Should be fixed by
https://github.com/lhotse-speech/lhotse/pull/862

**Comment by csukuangfj** [comment] 2022-10-26 16:14
Verified and the fix works.

**Closed** 2022-10-26 16:14 UTC
